name: CI Pipeline # name shown in GitHub UI

on: [push] # trigger: run on every push

jobs:
  hello: # job ID (you choose the name)
    runs-on: ubuntu-latest # runner: use a free Ubuntu machine

    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la
